# Generated by Django 5.2 on 2025-05-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='paises_visitados',
        ),
        migrations.AddField(
            model_name='user',
            name='countries_visited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
