# Generated by Django 5.2 on 2025-05-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_alter_itinerary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={},
        ),
    ]
