# Generated by Django 5.2 on 2025-05-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_alter_itinerary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destination'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participant'},
        ),
    ]
