# Generated by Django 5.2 on 2025-05-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_alter_destination_options_alter_participant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name': 'Itinerary', 'verbose_name_plural': 'Itinerary'},
        ),
    ]
