# Generated by Django 5.2 on 2025-05-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_alter_itinerary_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='creator_first_name',
            new_name='itinerary_name',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
