# Generated by Django 5.2 on 2025-05-22 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0007_rename_creator_first_name_itinerary_itinerary_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='destinations',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_list', to='itineraries.itinerary'),
        ),
    ]
