# Generated by Django 5.2 on 2025-05-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0008_itinerary_destinations_alter_destination_itinerary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='destinations',
            new_name='countries',
        ),
    ]
