# Generated by Django 5.2 on 2025-05-26 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0009_rename_destinations_itinerary_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countires_list', to='itineraries.itinerary'),
        ),
    ]
