from django.db import models
from apps.users.models.user import User

class SavedPlace(models.Model):
    savedPlaces_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='saved_places')
    place_id = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    rating = models.DecimalField(max_digits=2, decimal_places=1)
    address = models.TextField()
    PLACE_TYPES = [
        # Alojamientos
        ('lodging', 'Lodging'),
        ('hotel', 'Hotel'),
        ('motel', 'Motel'),
        ('resort_hotel', 'Resort Hotel'),
        ('hostel', 'Hostel'),
        ('bed_and_breakfast', 'Bed and Breakfast'),
        ('guest_house', 'Guest House'),
        ('campground', 'Campground'),
        ('mobile_home_park', 'Mobile Home Park'),
        ('cottage', 'Cottage'),
        ('extended_stay_hotel', 'Extended Stay Hotel'),
        ('farmstay', 'Farmstay'),
        ('budget_japanese_inn', 'Budget Japanese Inn'),
        ('japanese_inn', 'Japanese Inn'),
        ('inn', 'Inn'),
        ('private_guest_room', 'Private Guest Room'),
        ('rv_park', 'RV Park'),
        
        # Restauración / Gastronomía
        ('restaurant', 'Restaurant'),
        ('bar', 'Bar'),
        ('cafe', 'Cafe'),
        ('bakery', 'Bakery'),
        ('bagel_shop', 'Bagel Shop'),
        ('shopping_mall', 'Shopping Mall')
        ('bar_and_grill', 'Bar and Grill'),
        ('barbecue_restaurant', 'Barbecue Restaurant'),
        ('buffet_restaurant', 'Buffet Restaurant'),
        ('brunch_restaurant', 'Brunch Restaurant'),
        ('breakfast_restaurant', 'Breakfast Restaurant'),
        ('burger_restaurant', 'Burger Restaurant'),
        ('hamburger_restaurant', 'Hamburger Restaurant'),
        ('pub', 'Pub'),
        ('fine_dining_restaurant', 'Fine Dining Restaurant'),
        ('fast_food_restaurant', 'Fast Food Restaurant'),
        ('food_court', 'Food Court'),
        ('meal_takeaway', 'Meal Takeaway'),
        ('meal_delivery', 'Meal Delivery'),
        ('deli', 'Deli'),
        ('confectionery', 'Confectionery'),
        ('candy_store', 'Candy Store'),
        ('chocolate_shop', 'Chocolate Shop'),
        ('chocolate_factory', 'Chocolate Factory'),
        ('ice_cream_shop', 'Ice Cream Shop'),
        ('dessert_shop', 'Dessert Shop'),
        ('dessert_restaurant', 'Dessert Restaurant'),
        ('donut_shop', 'Donut Shop'),
        ('cafeteria', 'Cafeteria'),
        ('coffee_shop', 'Coffee Shop'),
        ('juice_shop', 'Juice Shop'),
        ('wine_bar', 'Wine Bar'),
        ('sushi_restaurant', 'Sushi Restaurant'),
        ('pizza_restaurant', 'Pizza Restaurant'),
        ('mexican_restaurant', 'Mexican Restaurant'),
        ('italian_restaurant', 'Italian Restaurant'),
        ('indian_restaurant', 'Indian Restaurant'),
        ('chinese_restaurant', 'Chinese Restaurant'),
        ('japanese_restaurant', 'Japanese Restaurant'),
        ('korean_restaurant', 'Korean Restaurant'),
        ('thai_restaurant', 'Thai Restaurant'),
        ('greek_restaurant', 'Greek Restaurant'),
        ('french_restaurant', 'French Restaurant'),
        ('spanish_restaurant', 'Spanish Restaurant'),
        ('american_restaurant', 'American Restaurant'),
        ('asian_restaurant', 'Asian Restaurant'),
        ('african_restaurant', 'African Restaurant'),
        ('brazilian_restaurant', 'Brazilian Restaurant'),
        ('lebanese_restaurant', 'Lebanese Restaurant'),
        ('middle_eastern_restaurant', 'Middle Eastern Restaurant'),
        ('mediterranean_restaurant', 'Mediterranean Restaurant'),
        ('vegan_restaurant', 'Vegan Restaurant'),
        ('vegetarian_restaurant', 'Vegetarian Restaurant'),
        ('afghani_restaurant', 'Afghani Restaurant'),
        ('acai_shop', 'Acai Shop'),
        ('cat_cafe', 'Cat Cafe'),
        ('dog_cafe', 'Dog Cafe'),

        # Actividades / Turismo
        ('tourist_attraction', 'Tourist Attraction'),
        ('point_of_interest', 'Point of Interest'),
        ('museum', 'Museum'),
        ('art_gallery', 'Art Gallery'),
        ('zoo', 'Zoo'),
        ('aquarium', 'Aquarium'),
        ('park', 'Park'),
        ('farm', 'Farm'),
        ('national_park', 'National Park'),
        ('state_park', 'State Park'),
        ('botanical_garden', 'Botanical Garden'),
        ('water_park', 'Water Park'),
        ('wildlife_park', 'Wildlife Park'),
        ('wildlife_refuge', 'Wildlife Refuge'),
        ('amusement_park', 'Amusement Park'),
        ('amusement_center', 'Amusement Center'),
        ('roller_coaster', 'Roller Coaster'),
        ('ferris_wheel', 'Ferris Wheel'),
        ('hiking_area', 'Hiking Area'),
        ('camping_cabin', 'Camping Cabin'),
        ('playground', 'Playground'),
        ('bowling_alley', 'Bowling Alley'),
        ('casino', 'Casino'),
        ('movie_theater', 'Movie Theater'),
        ('concert_hall', 'Concert Hall'),
        ('theater', 'Theater'),
        ('opera_house', 'Opera House'),
        ('philharmonic_hall', 'Philharmonic Hall'),
        ('planetarium', 'Planetarium'),
        ('marina', 'Marina'),
        ('picnic_ground', 'Picnic Ground'),
        ('off_roading_area', 'Off-Roading Area'),
        ('adventure_sports_center', 'Adventure Sports Center'),
        ('childrens_camp', 'Children\'s Camp'),
        ('community_center', 'Community Center'),
        ('visitor_center', 'Visitor Center'),
        ('event_venue', 'Event Venue'),
        ('wedding_venue', 'Wedding Venue'),
        ('monument', 'Monument'),
        ('historical_place', 'Historical Place'),
        ('historical_landmark', 'Historical Landmark'),
        ('cultural_center', 'Cultural Center'),
        ('cultural_landmark', 'Cultural Landmark'),
        ('religious_site', 'Religious Site'),
        ('church', 'Church'),
        ('synagogue', 'Synagogue'),
        ('mosque', 'Mosque'),
        ('hindu_temple', 'Hindu Temple'),
        ('library', 'Library'),
        ('art_studio', 'Art Studio'),
        ('dance_hall', 'Dance Hall'),
        ('comedy_club', 'Comedy Club'),
        ('karaoke', 'Karaoke'),
        ('video_arcade', 'Video Arcade'),
        ('internet_cafe', 'Internet Cafe'),
        ('banquet_hall', 'Banquet Hall'),
        ('auditorium', 'Auditorium'),
    ]
    place_type = models.CharField(max_length=50, choices=PLACE_TYPES)
    latitude = models.DecimalField(max_digits=30, decimal_places=20)
    longitude = models.DecimalField(max_digits=30, decimal_places=20)
    isSave = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Saved Place'
        verbose_name_plural = 'Saved Place'

    def __str__(self):
        return self.name