# Generated by Django 5.2 on 2025-04-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='firebase_email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
