# Generated by Django 5.2 on 2025-05-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Expense', 'verbose_name_plural': 'Expense'},
        ),
        migrations.AlterModelOptions(
            name='userexpense',
            options={'verbose_name': 'UserExpense', 'verbose_name_plural': 'UserExpense'},
        ),
    ]
