# Generated by Django 5.2 on 2025-05-14 19:15

import apps.itineraries.models.destination
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_expense_description_expense_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=apps.itineraries.models.destination.Destination),
        ),
    ]
