# Generated by Django 5.2 on 2025-05-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexpense',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
