# Generated by Django 5.2 on 2025-05-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_userexpense_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexpense',
            name='category',
            field=models.CharField(choices=[('Accommodation', 'Accommodation'), ('Activities', 'Activities'), ('Restaurants', 'Restaurants')], default='Accommodation', max_length=20),
        ),
    ]
