# Generated by Django 5.2 on 2025-05-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_remove_userexpense_category_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Equalitarian', 'Equalitarian'), ('Personalized', 'Personalized')], default='Equalitarian', max_length=20),
        ),
    ]
