# Generated by Django 5.2 on 2025-05-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_expense_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='type_expense',
        ),
    ]
