# Generated by Django 5.2 on 2025-06-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_rename_category_expense_type_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type_expense',
            field=models.CharField(choices=[('Equalitarian', 'Equalitarian'), ('Personalized', 'Personalized')], default='Personalized', max_length=20),
        ),
    ]
