# Generated by Django 5.2 on 2025-05-08 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('savedPlaces_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('address', models.TextField()),
                ('place_type', models.CharField(choices=[('lodging', 'Lodging'), ('hotel', 'Hotel'), ('motel', 'Motel'), ('resort_hotel', 'Resort Hotel'), ('hostel', 'Hostel'), ('bed_and_breakfast', 'Bed and Breakfast'), ('guest_house', 'Guest House'), ('campground', 'Campground'), ('mobile_home_park', 'Mobile Home Park'), ('cottage', 'Cottage'), ('extended_stay_hotel', 'Extended Stay Hotel'), ('farmstay', 'Farmstay'), ('budget_japanese_inn', 'Budget Japanese Inn'), ('japanese_inn', 'Japanese Inn'), ('inn', 'Inn'), ('private_guest_room', 'Private Guest Room'), ('rv_park', 'RV Park'), ('restaurant', 'Restaurant'), ('bar', 'Bar'), ('cafe', 'Cafe'), ('bakery', 'Bakery'), ('bagel_shop', 'Bagel Shop'), ('bar_and_grill', 'Bar and Grill'), ('barbecue_restaurant', 'Barbecue Restaurant'), ('buffet_restaurant', 'Buffet Restaurant'), ('brunch_restaurant', 'Brunch Restaurant'), ('breakfast_restaurant', 'Breakfast Restaurant'), ('burger_restaurant', 'Burger Restaurant'), ('hamburger_restaurant', 'Hamburger Restaurant'), ('pub', 'Pub'), ('fine_dining_restaurant', 'Fine Dining Restaurant'), ('fast_food_restaurant', 'Fast Food Restaurant'), ('food_court', 'Food Court'), ('meal_takeaway', 'Meal Takeaway'), ('meal_delivery', 'Meal Delivery'), ('deli', 'Deli'), ('confectionery', 'Confectionery'), ('candy_store', 'Candy Store'), ('chocolate_shop', 'Chocolate Shop'), ('chocolate_factory', 'Chocolate Factory'), ('ice_cream_shop', 'Ice Cream Shop'), ('dessert_shop', 'Dessert Shop'), ('dessert_restaurant', 'Dessert Restaurant'), ('donut_shop', 'Donut Shop'), ('cafeteria', 'Cafeteria'), ('coffee_shop', 'Coffee Shop'), ('juice_shop', 'Juice Shop'), ('wine_bar', 'Wine Bar'), ('sushi_restaurant', 'Sushi Restaurant'), ('pizza_restaurant', 'Pizza Restaurant'), ('mexican_restaurant', 'Mexican Restaurant'), ('italian_restaurant', 'Italian Restaurant'), ('indian_restaurant', 'Indian Restaurant'), ('chinese_restaurant', 'Chinese Restaurant'), ('japanese_restaurant', 'Japanese Restaurant'), ('korean_restaurant', 'Korean Restaurant'), ('thai_restaurant', 'Thai Restaurant'), ('greek_restaurant', 'Greek Restaurant'), ('french_restaurant', 'French Restaurant'), ('spanish_restaurant', 'Spanish Restaurant'), ('american_restaurant', 'American Restaurant'), ('asian_restaurant', 'Asian Restaurant'), ('african_restaurant', 'African Restaurant'), ('brazilian_restaurant', 'Brazilian Restaurant'), ('lebanese_restaurant', 'Lebanese Restaurant'), ('middle_eastern_restaurant', 'Middle Eastern Restaurant'), ('mediterranean_restaurant', 'Mediterranean Restaurant'), ('vegan_restaurant', 'Vegan Restaurant'), ('vegetarian_restaurant', 'Vegetarian Restaurant'), ('afghani_restaurant', 'Afghani Restaurant'), ('acai_shop', 'Acai Shop'), ('cat_cafe', 'Cat Cafe'), ('dog_cafe', 'Dog Cafe'), ('tourist_attraction', 'Tourist Attraction'), ('point_of_interest', 'Point of Interest'), ('museum', 'Museum'), ('art_gallery', 'Art Gallery'), ('zoo', 'Zoo'), ('aquarium', 'Aquarium'), ('park', 'Park'), ('farm', 'Farm'), ('national_park', 'National Park'), ('state_park', 'State Park'), ('botanical_garden', 'Botanical Garden'), ('water_park', 'Water Park'), ('wildlife_park', 'Wildlife Park'), ('wildlife_refuge', 'Wildlife Refuge'), ('amusement_park', 'Amusement Park'), ('amusement_center', 'Amusement Center'), ('roller_coaster', 'Roller Coaster'), ('ferris_wheel', 'Ferris Wheel'), ('hiking_area', 'Hiking Area'), ('camping_cabin', 'Camping Cabin'), ('playground', 'Playground'), ('bowling_alley', 'Bowling Alley'), ('casino', 'Casino'), ('movie_theater', 'Movie Theater'), ('concert_hall', 'Concert Hall'), ('theater', 'Theater'), ('opera_house', 'Opera House'), ('philharmonic_hall', 'Philharmonic Hall'), ('planetarium', 'Planetarium'), ('marina', 'Marina'), ('picnic_ground', 'Picnic Ground'), ('off_roading_area', 'Off-Roading Area'), ('adventure_sports_center', 'Adventure Sports Center'), ('childrens_camp', "Children's Camp"), ('community_center', 'Community Center'), ('visitor_center', 'Visitor Center'), ('event_venue', 'Event Venue'), ('wedding_venue', 'Wedding Venue'), ('monument', 'Monument'), ('historical_place', 'Historical Place'), ('historical_landmark', 'Historical Landmark'), ('cultural_center', 'Cultural Center'), ('cultural_landmark', 'Cultural Landmark'), ('religious_site', 'Religious Site'), ('church', 'Church'), ('synagogue', 'Synagogue'), ('mosque', 'Mosque'), ('hindu_temple', 'Hindu Temple'), ('library', 'Library'), ('art_studio', 'Art Studio'), ('dance_hall', 'Dance Hall'), ('comedy_club', 'Comedy Club'), ('karaoke', 'Karaoke'), ('video_arcade', 'Video Arcade'), ('internet_cafe', 'Internet Cafe'), ('banquet_hall', 'Banquet Hall'), ('auditorium', 'Auditorium')], max_length=50)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPlaceImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('place_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('address', models.TextField()),
                ('accomodation_type', models.CharField(choices=[('bed_and_breakfast', 'Bed and Breakfast'), ('budget_japanese_inn', 'Budget Japanese Inn'), ('campground', 'Campground'), ('camping_cabin', 'Camping Cabin'), ('cottage', 'Cottage'), ('extended_stay_hotel', 'Extended Stay Hotel'), ('farmstay', 'Farmstay'), ('guest_house', 'Guest House'), ('hostel', 'Hostel'), ('hotel', 'Hotel'), ('inn', 'Inn'), ('japanese_inn', 'Japanese Inn'), ('lodging', 'Lodging'), ('mobile_home_park', 'Mobile Home Park'), ('motel', 'Motel'), ('private_guest_room', 'Private Guest Room'), ('resort_hotel', 'Resort Hotel'), ('rv_park', 'RV Park')], max_length=50)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='itineraries.destination')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.TextField()),
                ('accommodation', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('place_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('address', models.TextField()),
                ('activity_type', models.CharField(choices=[('adventure_sports_center', 'Adventure Sports Center'), ('amphitheatre', 'Amphitheatre'), ('amusement_center', 'Amusement Center'), ('amusement_park', 'Amusement Park'), ('aquarium', 'Aquarium'), ('banquet_hall', 'Banquet Hall'), ('barbecue_area', 'Barbecue Area'), ('botanical_garden', 'Botanical Garden'), ('bowling_alley', 'Bowling Alley'), ('casino', 'Casino'), ('childrens_camp', "Children's Camp"), ('comedy_club', 'Comedy Club'), ('community_center', 'Community Center'), ('concert_hall', 'Concert Hall'), ('convention_center', 'Convention Center'), ('cultural_center', 'Cultural Center'), ('cycling_park', 'Cycling Park'), ('dance_hall', 'Dance Hall'), ('dog_park', 'Dog Park'), ('event_venue', 'Event Venue'), ('ferris_wheel', 'Ferris Wheel'), ('garden', 'Garden'), ('hiking_area', 'Hiking Area'), ('historical_landmark', 'Historical Landmark'), ('internet_cafe', 'Internet Cafe'), ('karaoke', 'Karaoke'), ('marina', 'Marina'), ('movie_rental', 'Movie Rental'), ('movie_theater', 'Movie Theater'), ('national_park', 'National Park'), ('night_club', 'Night Club'), ('observation_deck', 'Observation Deck'), ('off_roading_area', 'Off-Roading Area'), ('opera_house', 'Opera House'), ('park', 'Park'), ('farm', 'Farm'), ('philharmonic_hall', 'Philharmonic Hall'), ('picnic_ground', 'Picnic Ground'), ('planetarium', 'Planetarium'), ('plaza', 'Plaza'), ('roller_coaster', 'Roller Coaster'), ('skateboard_park', 'Skateboard Park'), ('state_park', 'State Park'), ('tourist_attraction', 'Tourist Attraction'), ('video_arcade', 'Video Arcade'), ('visitor_center', 'Visitor Center'), ('water_park', 'Water Park'), ('wedding_venue', 'Wedding Venue'), ('wildlife_park', 'Wildlife Park'), ('wildlife_refuge', 'Wildlife Refuge'), ('zoo', 'Zoo'), ('art_gallery', 'Art Gallery'), ('art_studio', 'Art Studio'), ('church', 'Church'), ('hindu_temple', 'Hindu Temple'), ('mosque', 'Mosque'), ('synagogue', 'Synagogue'), ('auditorium', 'Auditorium'), ('cultural_landmark', 'Cultural Landmark'), ('historical_place', 'Historical Place'), ('monument', 'Monument'), ('museum', 'Museum'), ('performing_arts_theater', 'Performing Arts Theater'), ('sculpture', 'Sculpture')], max_length=50)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='itineraries.destination')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.TextField()),
                ('activity', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('place_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('address', models.TextField()),
                ('restaurant_type', models.CharField(choices=[('acai_shop', 'Acai Shop'), ('afghani_restaurant', 'Afghani Restaurant'), ('african_restaurant', 'African Restaurant'), ('american_restaurant', 'American Restaurant'), ('asian_restaurant', 'Asian Restaurant'), ('bagel_shop', 'Bagel Shop'), ('bakery', 'Bakery'), ('bar', 'Bar'), ('bar_and_grill', 'Bar and Grill'), ('barbecue_restaurant', 'Barbecue Restaurant'), ('brazilian_restaurant', 'Brazilian Restaurant'), ('breakfast_restaurant', 'Breakfast Restaurant'), ('brunch_restaurant', 'Brunch Restaurant'), ('buffet_restaurant', 'Buffet Restaurant'), ('cafe', 'Cafe'), ('cafeteria', 'Cafeteria'), ('candy_store', 'Candy Store'), ('cat_cafe', 'Cat Cafe'), ('chinese_restaurant', 'Chinese Restaurant'), ('chocolate_factory', 'Chocolate Factory'), ('chocolate_shop', 'Chocolate Shop'), ('coffee_shop', 'Coffee Shop'), ('confectionery', 'Confectionery'), ('deli', 'Deli'), ('dessert_restaurant', 'Dessert Restaurant'), ('dessert_shop', 'Dessert Shop'), ('diner', 'Diner'), ('dog_cafe', 'Dog Cafe'), ('donut_shop', 'Donut Shop'), ('fast_food_restaurant', 'Fast Food Restaurant'), ('fine_dining_restaurant', 'Fine Dining Restaurant'), ('food_court', 'Food Court'), ('french_restaurant', 'French Restaurant'), ('greek_restaurant', 'Greek Restaurant'), ('hamburger_restaurant', 'Hamburger Restaurant'), ('ice_cream_shop', 'Ice Cream Shop'), ('indian_restaurant', 'Indian Restaurant'), ('indonesian_restaurant', 'Indonesian Restaurant'), ('italian_restaurant', 'Italian Restaurant'), ('japanese_restaurant', 'Japanese Restaurant'), ('juice_shop', 'Juice Shop'), ('korean_restaurant', 'Korean Restaurant'), ('lebanese_restaurant', 'Lebanese Restaurant'), ('meal_delivery', 'Meal Delivery'), ('meal_takeaway', 'Meal Takeaway'), ('mediterranean_restaurant', 'Mediterranean Restaurant'), ('mexican_restaurant', 'Mexican Restaurant'), ('middle_eastern_restaurant', 'Middle Eastern Restaurant'), ('pizza_restaurant', 'Pizza Restaurant'), ('pub', 'Pub'), ('ramen_restaurant', 'Ramen Restaurant'), ('restaurant', 'Restaurant'), ('sandwich_shop', 'Sandwich Shop'), ('seafood_restaurant', 'Seafood Restaurant'), ('spanish_restaurant', 'Spanish Restaurant'), ('steak_house', 'Steak House'), ('sushi_restaurant', 'Sushi Restaurant'), ('tea_house', 'Tea House'), ('thai_restaurant', 'Thai Restaurant'), ('turkish_restaurant', 'Turkish Restaurant'), ('vegan_restaurant', 'Vegan Restaurant'), ('vegetarian_restaurant', 'Vegetarian Restaurant'), ('vietnamese_restaurant', 'Vietnamese Restaurant'), ('wine_bar', 'Wine Bar')], max_length=50)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='itineraries.destination')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.TextField()),
                ('restaurant', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.restaurant')),
            ],
        ),
    ]
