# Generated by Django 5.2 on 2025-05-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='Activity',
        ),
    ]
