# Generated by Django 5.2 on 2025-05-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_activity_options_alter_activity_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
    ]
