# Generated by Django 5.2 on 2025-05-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_activity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={'verbose_name': 'Accommodation', 'verbose_name_plural': 'Accommodation'},
        ),
        migrations.AlterModelOptions(
            name='accommodationimage',
            options={'verbose_name': 'Accommodation Image', 'verbose_name_plural': 'Accommodation Image'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activity'},
        ),
        migrations.AlterModelOptions(
            name='activityimage',
            options={'verbose_name': 'Activity Image', 'verbose_name_plural': 'Activity Image'},
        ),
    ]
