# Generated by Django 5.2 on 2025-05-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_accommodation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurant'},
        ),
        migrations.AlterModelOptions(
            name='restaurantimage',
            options={'verbose_name': 'Restaurant Image', 'verbose_name_plural': 'Restaurant Image'},
        ),
        migrations.AlterModelOptions(
            name='savedplace',
            options={'verbose_name': 'Saved Place', 'verbose_name_plural': 'Saved Place'},
        ),
        migrations.AlterModelOptions(
            name='savedplaceimage',
            options={'verbose_name': 'Saved Place Image', 'verbose_name_plural': 'Saved Place Image'},
        ),
    ]
