# Generated by Django 5.2 on 2025-05-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_accommodation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='savedplace',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='savedplace',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
