# Generated by Django 5.2 on 2025-06-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_activity_latitude_alter_activity_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='isSave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='isSave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='isSave',
            field=models.BooleanField(default=False),
        ),
    ]
