# Generated by Django 5.2 on 2025-06-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_accommodation_issave_activity_issave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedplace',
            name='isSave',
            field=models.BooleanField(default=False),
        ),
    ]
